# Generated by Django 4.1.3 on 2022-12-20 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprocess_id', models.IntegerField()),
                ('step_id', models.IntegerField()),
                ('failure_mode', models.TextField()),
                ('found_in_other_steps', models.CharField(max_length=256, null=True)),
                ('potential_effect', models.TextField(null=True)),
                ('potential_causes', models.TextField(null=True)),
                ('severity', models.IntegerField(default=0, null=True)),
                ('rpn', models.FloatField(default=0, null=True)),
                ('current_mitigation', models.TextField(null=True)),
                ('mitigation_strategy', models.TextField(null=True)),
                ('process_type', models.CharField(max_length=256, null=True)),
                ('software', models.CharField(max_length=256, null=True)),
                ('abr', models.CharField(max_length=256, null=True)),
                ('process_id', models.CharField(max_length=20, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(null=True)),
                ('software_solution', models.TextField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_fm',
                'ordering': ['subprocess_id', 'step_id', 'severity'],
            },
        ),
    ]
